name: CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install tools and package
        run: |
          python -m pip install -U pip
          python -m pip install -U ruff mypy pytest pytest-cov
          python -m pip install -e .
          # Optional: docs build check on latest only
          if [[ "${{ matrix.python-version }}" == "3.12" ]]; then
            python -m pip install .[docs]
            mkdocs build --strict
          fi

      - name: Ruff (lint)
        run: ruff check .

      - name: Ruff (format check)
        run: ruff format --check .

      - name: Mypy (types)
        run: mypy contextforge

      - name: Tests (pytest + coverage)
        run: pytest

      - name: Upload coverage XML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
